// <auto-generated />
namespace dimain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ver1_datacache : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ver1_datacache));
        
        string IMigrationMetadata.Id
        {
            get { return "201410112312461_ver1_datacache"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
